from database import SessionLocal
from models import Posts, Users
from models.enums import NotificationType
from modules import logging
from repository.notification_repository import _create_notification
from utils import get_usernames
from utils.extensions import socketio

Log = logging.getLogger(__name__)

ignore_username = ["Nara"]


def suggestion(
    post_id: int,
    user_id: list[int],  # list of user IDs to whom the suggestion is made
    text: str,  # title of the post or ""
) -> None | Exception:
    notice = {
        "post_id": post_id,
        "text": text[150] if len(text) > 150 else text,  # Short preview of the text,
    }

    for _user_id in user_id:
        # Create the notification using the createNotification function
        _create_notification(
            user_id=_user_id,
            author_user_id=None,  # This notification generated by system
            notice=notice,
            type=NotificationType.suggestion,
        )

        # Emit the notification to the user via SocketIO
        socketio.emit(
            "notification",
            {"type": NotificationType.suggestion.value, "notice": notice},
            to=str(_user_id),
            namespace="/notifications",
        )


def reply_n_mention(
    parent_post_id: int | None,
    post_id: int,
    session_user_id: int,  # user ID of post/reply author who mentioned others in the thread
    mentioned_usernames_by_system: list[str]
    | None,  # list of usernames mentioned by system in the reply in the thread
    text: str = "",  # text of the post or ""
) -> None | Exception:
    session = SessionLocal()
    try:
        _mentioned_usernames_by_system: list[str] = (
            mentioned_usernames_by_system if mentioned_usernames_by_system else []
        )

        # Common fn to send notification
        def create_mention_notification(
            mentioned_username: str,  # username of whom is goinn to recieve it
            _author_user_id: int,
            _notice: dict,
            type: NotificationType,
        ):
            # Find the user ID of the mentioned username
            result = (
                session.query(Users.id)
                .filter(Users.username == mentioned_username)
                .first()
            )
            # User iD of the mentioned user, if found, else None
            user_id: int | None = result.id if result else None

            # If the mentioned user is found, create a notification for them
            if user_id:
                # Create the notification using the createNotification function
                _create_notification(
                    user_id=user_id,
                    author_user_id=session_user_id,
                    notice=_notice,
                    type=type,
                )
                # Emit the notification to the user via SocketIO
                socketio.emit(
                    "notification",
                    {"type": type.value, "notice": _notice},
                    to=str(user_id),
                    namespace="/notifications",
                )

        ## Reply --
        # Extract mentioned usernames from the text
        mentioned_usernames = get_usernames(text)

        # Get the username of the user who mentioned others
        result = (
            session.query(Users.username).filter(Users.id == session_user_id).first()
        )
        # Get the username of the user who mentioned others
        mentioned_by_username = result[0] if result else None

        # Create notifications for each mentioned user by the system (e.g., if the system automatically mentions users in a thread)
        for mentioned_username in _mentioned_usernames_by_system:
            if mentioned_by_username == mentioned_username:
                continue  # Skip if the user mentioned himself

            if mentioned_username in ignore_username:
                continue

            notice = {
                # Post ID where the user was mentioned
                "post_id": post_id,
                "text": text[150]
                if len(text) > 150
                else text,  # Short preview of the text
            }
            create_mention_notification(
                mentioned_username,
                session_user_id,
                notice,
                NotificationType.reply,
            )

        # Create notifications for each mentioned user
        for mentioned_username in mentioned_usernames:
            if mentioned_username in _mentioned_usernames_by_system:
                continue  # Skip if the username is already mentioned by the system

            if mentioned_by_username == mentioned_username:
                continue  # Skip if the user mentioned himself

            if mentioned_username in ignore_username:
                continue

            notice = {
                # Post ID where the user was mentioned
                "post_id": post_id,
                "text": text[150]
                if len(text) > 150
                else text,  # Short preview of the text
            }
            create_mention_notification(
                mentioned_username,
                session_user_id,
                notice,
                NotificationType.mention,
            )

    except Exception as e:
        Log.critical(str(e))
        raise
    finally:
        session.close()


def follow(user_id: int, session_user_id: int) -> None:
    session = SessionLocal()
    try:
        user = session.query(Users).filter(Users.id == session_user_id).first()
        if user is None:
            return
        notice = {
            "username": user.username,
            "text": f"{user.username} started following you.",
        }
        _create_notification(
            user_id=user_id,
            author_user_id=session_user_id,
            notice={},  # Leave it empty, let handle by frontend completely
            type=NotificationType.follow,
        )
        # Emit the notification to the user via SocketIO
        socketio.emit(
            "notification",
            {"type": NotificationType.follow.value, "notice": notice},
            to=str(user_id),
            namespace="/notifications",
        )
    except Exception:
        raise
    finally:
        session.close()


def like(post_id: int, session_user_id: int) -> None:
    session = SessionLocal()
    try:
        post = session.query(Posts).filter(Posts.id == post_id).first()
        if post is None:
            return
        preview_text = ""
        if post.text:
            preview_text = post.text[150] if len(post.text) > 150 else post.text

        notice = {
            # post id of the post
            "post_id": post_id,
            # Post content text
            "text": preview_text,  # Short preview of the text,
        }
        _create_notification(
            user_id=post.user_id,
            author_user_id=session_user_id,
            notice=notice,
            type=NotificationType.like,
        )
        # Emit the notification to the user via SocketIO
        socketio.emit(
            "notification",
            {"type": NotificationType.like.value, "notice": notice},
            to=str(post.user_id),
            namespace="/notifications",
        )
    except Exception:
        raise
    finally:
        session.close()


def repost(post_id: int, session_user_id: int) -> None:
    session = SessionLocal()
    try:
        post = session.query(Posts).filter(Posts.id == post_id).first()
        if post is None:
            return
        preview_text = ""
        if post.text:
            preview_text = post.text[150] if len(post.text) > 150 else post.text
        notice = {
            # post id of the post
            "post_id": post_id,
            # Post content text
            "text": preview_text,  # Short preview of the text,
        }
        _create_notification(
            user_id=post.user_id,
            author_user_id=session_user_id,
            notice=notice,
            type=NotificationType.repost,
        )

        # Emit the notification to the user via SocketIO
        socketio.emit(
            "notification",
            {"type": NotificationType.repost.value, "notice": notice},
            to=str(post.user_id),
            namespace="/notifications",
        )
    except Exception:
        raise
    finally:
        session.close()


def warning(text: str) -> None:
    # TODO: Implement the warning notification logic
    notice = {
        "text": text,
    }


def danger(text: str) -> None:
    # TODO: Implement the danger notification logic
    notice = {
        "text": text,
    }


def system_update(text: str) -> None:
    # TODO: Implement the system update notification logic
    notice = {
        "text": text,
    }
